site_name: Pythonによる時系列予測

nav:
  - はじめに: index.md
  - "第2章 単純な未来予測": chapter02.ipynb
  - "第3章 ランダムウォーク": chapter03.ipynb
  - "第4章 移動平均プロセスのモデル化": chapter04.ipynb
  - "第5章 自己回帰プロセスのモデル化": chapter05.ipynb
  - "第6章 複雑な時系列のモデル化": chapter06.ipynb
  - "第7章 非定常時系列の予測": chapter07.ipynb
  - "第8章 季節性の考慮": chapter08.ipynb
  - "第9章 モデルへの外部変数の追加": chapter09.ipynb

theme:
  name: material

use_directory_urls: false

plugins:
  - mkdocs-jupyter